service: ${file(./config.yml):service_name} # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  stage: stage # NOTE: Override this option at package.json with CLI-command
  region: us-east-1

# you can add packaging information here
package:
  artifact: dist.zip

functions:
  ssr:
    handler: handler.ssr
    events:
      - http:
          method: get
          path: ${self:service}
      - http:
          method: any
          path: "${self:service}/{proxy+}"

resources:
  Resources: ${file(cloudformation.json)}
